version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust based on your Node.js version
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the NestJS application...
      - npm run build
      - echo Running tests...
      - npm run test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist  # Output directory

cache:
  paths:
    - node_modules/**/*
